### ISSUE TITLE
Charm dependency updates

### ISSUE THREAD

**Issue by dmzoneill** [Juniper/contrail-charms#108]
Hi,

If you could kindly confirm the correct backup operation for contrail Cassandra:
The contrail guide here:
https://www.juniper.net/documentation/en_US/contrail19/topics/concept/backup-using-json-40.html
references the tool db_json_exim.py as the preferred method.

However this is not present in any of the contrail containers.
It also fails to install via pypi.

Thank you

**check containers for module**
```
root@control-9:/home/ubuntu# for X in `docker ps -aq`; do docker exec -it $X python -c "cfgm-common"; done 
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Error response from daemon: Container e1d16f1f65745155033dd03c4f9b27ade3b62dbbd053f33191ba28a69c370f37 is not running
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Error response from daemon: Container 044692d87d6c2eacc4f7c157dd5be53f9dbad68e56927606c4fccb8f453c0d57 is not running
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown
Error response from daemon: Container 752b0d9e9ef8f67131941fec2ae0a91f297cc293857e77c2a54d2369549469a0 is not running
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cfgm' is not defined
Error response from daemon: Container 483c202ac4e0ee1b25a29923cffa4bf621fcc81c0a1698e3e7bae33e7747dbb8 is not running
```

**install failure**
```
root@control-9:/# export https_proxy="http://172.23.29.155:3128/"
root@control-9:/# pip3 install -i https://test.pypi.org/simple/ cfgm-common
Collecting cfgm-common
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 588, in urlopen
    self._prepare_proxy(conn)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 803, in _prepare_proxy
    conn.connect()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 291, in connect
    self._tunnel()
  File "/usr/lib/python3.5/http/client.py", line 832, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
root@control-9:/# pip install -i https://test.pypi.org/simple/ cfgm-common
Collecting cfgm-common
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by Andrey-mp** [comment]
ubuntu@jc5-cont-1:~$ sudo docker exec -it configapi_api_1 bash

(config-api)[root@jc5-cont-1 /]$ ll /usr/lib/python2.7/site-packages/cfgm_common/db_json_exim.py
-rw-r--r-- 1 root root 9930 Aug 13 06:24 /usr/lib/python2.7/site-packages/cfgm_common/db_json_exim.py

(config-api)[root@jc5-cont-1 /]$ python /usr/lib/python2.7/site-packages/cfgm_common/db_json_exim.py --help
usage: db_json_exim.py [-h] [--api-conf API_CONF] [--verbose] [--debug]
                       [--import-from FILE] [--export-to FILE]
                       [--omit-keyspaces [FILE [FILE ...]]]

optional arguments:
  -h, --help            show this help message and exit
  --api-conf API_CONF   Path to contrail-api conf file, default /etc/contrail
                        /contrail-api.conf
  --verbose             Run in verbose/INFO mode, default False
  --debug               Run in debug mode, default False
  --import-from FILE    Import from this json file to database
  --export-to FILE      Export from database to this json file
  --omit-keyspaces [FILE [FILE ...]]
                        List of keyspaces to omit in export/import
(config-api)[root@jc5-cont-1 /]$ python /usr/lib/python2.7/site-packages/cfgm_common/db_json_exim.py --export-to backup


(config-api)[root@jc5-cont-1 /]$ ll backup
-rw-r--r--   1 root root 1041447 Aug 15 12:32 backup

**Comment by dmzoneill** [comment]
thank you!
