### ISSUE TITLE
The 'cliff' distribution was not found and is required by ContrailConfigCli

### ISSUE THREAD

**Issue by dmzoneill** [Juniper/contrail-charms#134]
Hi,

I'm attempting to delete some virtual routers as described here
https://contrail-api-cli.readthedocs.io/en/latest/howto_api.html
```
contrail-api-cli shell
admin@localhost /> ls virtual-router
virtual-router/7c5d76a8-7ca3-43a6-bee6-154f84db977e
virtual-router/37fc1054-0d25-4a2d-aa42-9e202b5dfa3a
```
Getting the following error:
```
(config-api)[root@control-8 /]$ contrail-api-cli      
Traceback (most recent call last):
  File "/usr/bin/contrail-api-cli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cliff' distribution was not found and is required by ContrailConfigCli
(config-api)[root@control-8 /]$ exit

```

**Comment by Andrey-mp** [comment]
Hi @dmzoneill ,
I think it's not a charm issue. It's a general contail issue.
and I didn't find where this cmd can be run (which contianer)

**Comment by Andrey-mp** [comment]
looks like this tool works but is not supported in latest releases -

$ contrail-api-cli --help

Commands:
  read cpu load information          sandesh request to get cpu load info      


$ contrail-api-cli read
{
    "h3": "Sandesh Request \"CpuLoadInfoReq\" not implemented"
}
