### ISSUE TITLE
When upgrading contrail from 5.0.2 to 19.12 contrail-status fails on analytics units

### ISSUE THREAD

**Issue by peppepetra** [Juniper/contrail-charms#146]
After the upgrade contrail status fails with:

root@juju-073f4e-8-kvm-1:/home/ubuntu# contrail-status
Traceback (most recent call last):
  File "/root/contrail-status.py", line 595, in <module>
    main()
  File "/root/contrail-status.py", line 547, in main
    print_containers(containers)
  File "/root/contrail-status.py", line 498, in print_containers
    cl = 2 + len(item[i])
TypeError: object of type 'NoneType' has no len()

To workaround that we had to manually stop and remove the leftovers containers still running on version 5.0.2.

Example of running containers:

root@juju-073f4e-6-kvm-2:/home/ubuntu# docker ps -a | grep "5.0"
73b4da653fe8        hub.juniper.net/contrail/contrail-analytics-alarm-gen:5.0.2-0.360-queens        "/entrypoint.sh /usr…"   5 months ago        Up 4 minutes                                        analytics_alarm-gen_1
160ab5840153        hub.juniper.net/contrail/contrail-analytics-snmp-collector:5.0.2-0.360-queens   "/entrypoint.sh /usr…"   5 months ago        Up 4 weeks                                          analytics_snmp-collector_1
446214c279fb        hub.juniper.net/contrail/contrail-analytics-topology:5.0.2-0.360-queens         "/entrypoint.sh /usr…"   5 months ago        Up 4 weeks                                          analytics_topology_1
fefdbe8a62e0        hub.juniper.net/contrail/contrail-analytics-query-engine:5.0.2-0.360-queens     "/entrypoint.sh /usr…"   5 months ago        Up 4 weeks                                          analytics_query-engine_1

**Comment by Andrey-mp** [comment]
btw - there is no procedure for upgrade. it was not developed and tested.
