### ISSUE TITLE
Contrail Web UI Config DB sub menus give 'Error: undefined'

### ISSUE THREAD

**Issue by bbcmicrocomputer** [Juniper/contrail-charms#5]
Deploying Contrail 4.0.2 using 4.0.2 charms (tag v4.0.2) using the attached bundle.

When using the Contrail Web UI, all Settings -> Config DB sub menus (FQ Name Table, UUID Table, Shared Table) produce an 'Error: undefined' message (attached screenshot).

The logs from contrail-webui service on the controller container show:
```
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: { [Error: All host(s) tried for query failed. First host tried, 192.168.122.34:9041: AuthenticationError: Authentication provider not set. See innerErrors.]
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:   innerErrors:
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:    { '192.168.122.34:9041':
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:       { [AuthenticationError: Authentication provider not set]
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         name: 'AuthenticationError',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         stack: 'Error: Authentication provider not set\n    at AuthenticationError.DriverError (/usr/lib64/node_modules/cassandra-driver/lib/errors.js:14:19)\n    at new AuthenticationErro
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         message: 'Authentication provider not set',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         info: 'Represents an authentication error from the driver or from a Cassandra node.' },
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:      '192.168.122.35:9041':
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:       { [AuthenticationError: Authentication provider not set]
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         name: 'AuthenticationError',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         stack: 'Error: Authentication provider not set\n    at AuthenticationError.DriverError (/usr/lib64/node_modules/cassandra-driver/lib/errors.js:14:19)\n    at new AuthenticationErro
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         message: 'Authentication provider not set',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         info: 'Represents an authentication error from the driver or from a Cassandra node.' },
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:      '192.168.122.36:9041':
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:       { [AuthenticationError: Authentication provider not set]
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         name: 'AuthenticationError',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         stack: 'Error: Authentication provider not set\n    at AuthenticationError.DriverError (/usr/lib64/node_modules/cassandra-driver/lib/errors.js:14:19)\n    at new AuthenticationErro
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         message: 'Authentication provider not set',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:         info: 'Represents an authentication error from the driver or from a Cassandra node.' } },
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:   info: 'Represents an error when a query cannot be performed because no host is available or could be reached by the driver.',
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:   message: 'All host(s) tried for query failed. First host tried, 192.168.122.34:9041: AuthenticationError: Authentication provider not set. See innerErrors.' }
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: 01/31/2018 03:15:59 PM - error: undefined
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: 01/31/2018 03:15:59 PM - error: undefined
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: /usr/lib64/node_modules/connect-redis/node_modules/redis/index.js:531
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:             throw err;
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:                   ^
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: TypeError: Cannot call method 'toString' of undefined
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at ServerResponse.writeHead (http.js:1183:45)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at ServerResponse.res.writeHead (/usr/lib64/node_modules/express/node_modules/connect/lib/patch.js:75:22)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at ServerResponse._implicitHeader (http.js:1134:8)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at ServerResponse.res.write (/usr/lib64/node_modules/express/node_modules/connect/lib/middleware/compress.js:79:34)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at ServerResponse.res.end (/usr/lib64/node_modules/express/node_modules/connect/lib/middleware/compress.js:86:23)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at /usr/lib64/node_modules/express/node_modules/connect/lib/middleware/session.js:282:13
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at /usr/lib64/node_modules/connect-redis/lib/connect-redis.js:169:18
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at try_callback (/usr/lib64/node_modules/connect-redis/node_modules/redis/index.js:528:9)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at RedisClient.return_reply (/usr/lib64/node_modules/connect-redis/node_modules/redis/index.js:598:13)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]:     at RedisReplyParser.<anonymous> (/usr/lib64/node_modules/connect-redis/node_modules/redis/index.js:271:14)
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: 01/31/2018 03:15:59 PM - debug: The worker #54 has disconnected.
Jan 31 15:15:59 vm01 contrailWebServer.sh[38364]: 01/31/2018 03:15:59 PM - error: The worker #54 has exited with exit code 8
```
![screenshot from 2018-01-31 14-44-33](https://user-images.githubusercontent.com/6774503/35634740-53633520-06a4-11e8-90b4-df8a840d722d.png)
[contrail-docker-bundle-ha-ocata.yaml.txt](https://github.com/Juniper/contrail-charms/files/1682438/contrail-docker-bundle-ha-ocata.yaml.txt)

**Comment by Andrey-mp** [comment]
not a charms bug.
bug is inside webui module.
https://bugs.launchpad.net/juniperopenstack/+bug/1746719

**Comment by Andrey-mp** [comment]
works well in latest internal build for 4.1.1
