### ISSUE TITLE
replacing an analyticsdb unit requires manual work

### ISSUE THREAD

**Issue by aieri** [Juniper/contrail-charms#83]
After removing and redeploying an analyticsdb unit the following scenario can be observed:

On the redeployed unit:
```
INFO  [main] 2019-07-09 14:22:25,472 StorageService.java:1449 - JOINING: Starting to bootstrap...
Exception (java.lang.RuntimeException) encountered during startup: A node required to move the data consistently is down (/172.16.138.142). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
ERROR [main] 2019-07-09 14:22:25,502 CassandraDaemon.java:708 - Exception encountered during startup
java.lang.RuntimeException: A node required to move the data consistently is down (/172.16.138.142). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
at org.apache.cassandra.dht.RangeStreamer.getAllRangesWithStrictSourcesFor(RangeStreamer.java:294) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.dht.RangeStreamer.addRanges(RangeStreamer.java:177) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.dht.BootStrapper.bootstrap(BootStrapper.java:87) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1501) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:977) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.StorageService.initServer(StorageService.java:682) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.StorageService.initServer(StorageService.java:613) ~[apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:379) [apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602) [apache-cassandra-3.11.2.jar:3.11.2]
at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691) [apache-cassandra-3.11.2.jar:3.11.2]
```
On a surviving unit:
```
$ docker exec -it analyticsdatabase_cassandra_1 nodetool status -p 7200
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID Rack
UN  172.16.139.12   178.53 GiB  256          70.5% 93b92df0-73d2-48f2-a72f-b855da2ed276  rack1
UN  172.16.138.205  168.27 GiB  256          66.4% 1f77bdbe-5166-4cd1-8ffd-c5c842298bb9  rack1
DN  172.16.138.142  72.19 GiB  256          63.1% 7760de63-8dec-4148-8a9f-7fef2a3c66e0  rack1
```
Please note that 172.16.138.142 is the IP of the unit that got removed.
In order to have the new node join the cluster it is necessary to remove the old node with `nodetool removenode` first.

**Comment by dmzoneill** [comment]
fix

```
docker exec -it 45626105f62a bash
sed -i 's/7200}"/7200} -Dcassandra.consistent.rangemovement=false/'  /contrail-entrypoint.sh
exit
docker restart 45626105f62a 

docker exec -it 45626105f62a bash
root@juju-073f4e-5-kvm-0:/# nodetool status -p 7200
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
UJ  172.16.139.16   10.05 GiB  256          ?                 bd0f91f1-80da-4274-8f9d-6fe5ec747050  rack1
UN  172.16.139.12   102.67 GiB  256          70.5%             93b92df0-73d2-48f2-a72f-b855da2ed276  rack1
UN  172.16.138.205  10.68 GiB  256          66.4%             1f77bdbe-5166-4cd1-8ffd-c5c842298bb9  rack1
DN  172.16.138.142  ?          256          63.1%             7760de63-8dec-4148-8a9f-7fef2a3c66e0  rack1

#Remove the broken node, not the command will hang #https://stackoverflow.com/questions/25943261/nodetool-removenode-stuck-during-removal


root@juju-073f4e-5-kvm-0:/# nodetool removenode 7760de63-8dec-4148-8a9f-7fef2a3c66e0 -p 7200
^C

root@juju-073f4e-5-kvm-0:/# nodetool removenode force -p 7200
RemovalStatus: Removing token (-9176995134664024962). Waiting for replication confirmation from [/172.16.139.12,/172.16.138.205].

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns (effective)  Host ID                               Rack
UN  172.16.139.16   9.22 GiB   256          65.6%             bd0f91f1-80da-4274-8f9d-6fe5ec747050  rack1
UN  172.16.139.12   102.67 GiB  256          66.5%             93b92df0-73d2-48f2-a72f-b855da2ed276  rack1
UN  172.16.138.205  10.68 GiB  256          68.0%             1f77bdbe-5166-4cd1-8ffd-c5c842298bb9  rack1
```
