### ISSUE TITLE
Config- changed Event failed to update docker-compose file on master juju unit

### ISSUE THREAD

**Issue by dmzoneill** [Juniper/contrail-charms#87]
**Split cluster due to failed update of endpoints**

**Short Description:**
In the relation changed event on juju master unit **contrail-anaylticsdb/1**, the file **/etc/contrail/analytics_database/docker-compose.yaml** failed to update correclty, resulting in broken cluster, due to bad updates for **"my-ids"** and **zoo.conf**
  
**Platform:**
- ubuntu - bionic Ubuntu 18.04.2 LTS

**Juju Version**
- 2.6.5-bionic-amd64

**Juju charms**
```
contrail-agent                 5.0-360.el7    active      10  contrail-agent                 jujucharms    1  ubuntu  
contrail-agent-sriov           5.0-360.el7    active       2  contrail-agent                 jujucharms    1  ubuntu  
contrail-analytics             5.0-360.el7    active       2  contrail-analytics             jujucharms    0  ubuntu  
contrail-analyticsdb                          blocked      3  contrail-analyticsdb           jujucharms    0  ubuntu  
contrail-controller            5.0-360.el7    active       3  contrail-controller            jujucharms    0  ubuntu  
contrail-haproxy                              unknown      3  haproxy                        jujucharms   48  ubuntu  
contrail-keystone-auth                        active       3  contrail-keystone-auth         jujucharms    0  ubuntu  
contrail-openstack             5.0-360.el7    active      18  contrail-openstack             jujucharms    0  ubuntu  
```

**Long descrption**
During a unit failure, engineers added a unit to the **contrail-analyticsdb** unit and remove the broken one.  This moved the cluster through a number of state changes 

**# state 1** 
```
'analyticsdb_servers': [u'172.16.138.142', '172.16.138.205', u'172.16.139.12']
```
**# state 2**
```
'analyticsdb_servers': ['172.16.138.205', u'172.16.139.12'],

2019-07-08 16:50:01 INFO juju-log New lines set:
      - KAFKA_NODES=172.16.138.205,172.16.139.12
      - ZOOKEEPER_NODES=172.16.138.205,172.16.139.12
      - CASSANDRA_SEEDS=172.16.138.205,172.16.139.12

2019-07-08 16:50:01 INFO juju-log Old lines set:
      - ZOOKEEPER_NODES=172.16.138.142,172.16.138.205,172.16.139.12
      - CASSANDRA_SEEDS=172.16.138.142,172.16.138.205,172.16.139.12
      - KAFKA_NODES=172.16.138.142,172.16.138.205,172.16.139.12
```
**# state 3**
```
'analyticsdb_servers': ['172.16.138.205', u'172.16.139.12', u'172.16.139.16'],

2019-07-08 16:54:45 INFO juju-log New lines set:
ANALYTICSDB_NODES=172.16.138.205,172.16.139.12,172.16.139.16

2019-07-08 16:54:45 INFO juju-log Old lines set:
ANALYTICSDB_NODES=172.16.138.205,172.16.139.12

2019-07-08 16:54:45 INFO juju-log Configuration file has been changed.
2019-07-08 16:54:45 INFO juju-log Render and store new configuration: /etc/contrail/analytics_database/docker-compose.yaml
2019-07-08 16:54:45 DEBUG juju-log Writing file /etc/contrail/analytics_database/docker-compose.yaml root:root 444
2019-07-08 16:54:46 INFO juju-log New lines set:
      - KAFKA_NODES=172.16.138.205,172.16.139.12,172.16.139.16
      - CASSANDRA_SEEDS=172.16.138.205,172.16.139.12,172.16.139.16
      - ZOOKEEPER_NODES=172.16.138.205,172.16.139.12,172.16.139.16

2019-07-08 16:54:46 INFO juju-log Old lines set:
      - KAFKA_NODES=172.16.138.205,172.16.139.12
      - ZOOKEEPER_NODES=172.16.138.205,172.16.139.12
      - CASSANDRA_SEEDS=172.16.138.205,172.16.139.12
```

the resulting juju status looked like this
```
contrail-analyticsdb/1*           blocked   idle   7/kvm/1   172.16.138.205                                           Missing cloud_orchestrator info in relation with contrail-controller.
  canonical-livepatch/54          active    idle             172.16.138.205                                           Running kernel 4.15.0-47.50-generic, patchState: nothing-to-apply
  landscape-client/106            active    idle             172.16.138.205                                           System successfully registered
  nrpe-kvm-guest/7                active    idle             172.16.138.205  icmp,5666/tcp                            ready
  ntp-lp1817516/6                 active    idle             172.16.138.205  123/udp                                  ntp: Ready
contrail-analyticsdb/2            blocked   idle   8/kvm/1   172.16.139.12                                            Missing cloud_orchestrator info in relation with contrail-controller.
  canonical-livepatch/51          active    idle             172.16.139.12                                            Running kernel 4.15.0-47.50-generic, patchState: nothing-to-apply
  landscape-client/102            active    idle             172.16.139.12                                            System successfully registered
  nrpe-kvm-guest/4                active    idle             172.16.139.12   icmp,5666/tcp                            ready
  ntp-lp1817516/8*                active    idle             172.16.139.12   123/udp                                  ntp: Ready
contrail-analyticsdb/5            waiting   idle   5/kvm/0   172.16.139.16                                            nodemgr is not ready. Reason: (Cassandra state detected DOWN. )
  canonical-livepatch/67          active    idle             172.16.139.16                                            Running kernel 4.15.0-54.58-generic, patchState: nothing-to-apply
  landscape-client/133            active    idle             172.16.139.16                                            System successfully registered
  nrpe-kvm-guest/13               active    idle             172.16.139.16   icmp,5666/tcp                            ready
  ntp-lp1817516/22                active    idle             172.16.139.16   123/udp                                  ntp: Ready
```

For the period of a number of minutes the zookeeper configuration references **2 IPS** addresses during which time the files **zoo.conf** and **myid** updated inside the containers

E.g (this is fixed, as we had to fix it in a hurry)
```
bash-4.3# cat zoo.cfg 
clientPort=2182
dataDir=/data
dataLogDir=/datalog
tickTime=2000
initLimit=5
syncLimit=2
maxClientCnxns=60
server.1=172.16.139.12:4888:5888
server.2=172.16.138.205:4888:5888
# was missing
server.3=172.16.139.16:4888:5888

bash-4.3# cat /data/myid 
2
```

Due to the ordering of the **myids** and the generation of the **zoo.conf** eventually the cluster came back up with **3 ips.**  However the **MYIDS** conflicted and some machines where trying to bind to **IP/PORT** (socket on differnet mahcines).

```
2019-07-08 23:04:19,800 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2182:QuorumPeer@865] - LOOKING
2019-07-08 23:04:19,803 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2182:FastLeaderElection@818] - New election. My id =  3, proposed zxid=0x0
2019-07-08 23:04:19,812 [myid:3] - WARN  [WorkerSender[myid=3]:QuorumCnxManager@588] - Cannot open channel to 1 at election address /172.16.138.205:5888
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:562)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:538)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
        at java.lang.Thread.run(Thread.java:748)


2019-07-09 14:09:47,308 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2182:NIOServerCnxnFactory@192] - Accepted socket connection from /172.16.138.206:53694
2019-07-09 14:09:47,310 [myid:3] - INFO  [ListenerThread:QuorumCnxManager$Listener@739] - My election bind port: /172.16.139.16:5888
2019-07-09 14:09:47,312 [myid:3] - ERROR [/172.16.139.16:5888:QuorumCnxManager$Listener@763] - Exception while listening
java.net.BindException: Address not available (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.bind(ServerSocket.java:329)


2019-07-09 14:09:46,920 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: 172.16.139.16 to address: /172.16.139.16
2019-07-09 14:09:46,920 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: 172.16.139.12 to address: /172.16.139.12
2019-07-09 14:09:46,921 [myid:] - INFO  [main:QuorumPeer$QuorumServer@167] - Resolved hostname: 172.16.138.205 to address: /172.16.138.205
2019-07-09 14:09:46,921 [myid:] - INFO  [main:QuorumPeerConfig@396] - Defaulting to majority quorums
2019-07-09 14:09:46,924 [myid:3] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2019-07-09 14:09:46,924 [myid:3] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 0
2019-07-09 14:09:46,924 [myid:3] - INFO  [main:DatadirCleanupManager@101] - Purge task is not scheduled.
2019-07-09 14:09:46,937 [myid:3] - INFO  [main:QuorumPeerMain@127] - Starting quorum peer
2019-07-09 14:09:46,948 [myid:3] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2182
2019-07-09 14:09:46,961 [myid:3] - INFO  [main:QuorumPeer@1134] - minSessionTimeout set to -1
2019-07-09 14:09:46,961 [myid:3] - INFO  [main:QuorumPeer@1145] - maxSessionTimeout set to -1
2019-07-09 14:09:46,961 [myid:3] - INFO  [main:QuorumPeer@1419] - QuorumPeer communication is not secured!
2019-07-09 14:09:46,961 [myid:3] - INFO  [main:QuorumPeer@1448] - quorum.cnxn.threads.size set to 20
2019-07-09 14:09:46,965 [myid:3] - INFO  [main:FileSnap@83] - Reading snapshot /data/version-2/snapshot.1900000227
2019-07-09 14:09:47,308 [myid:3] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2182:NIOServerCnxnFactory@192] - Accepted socket connection from /172.16.138.206:53694
2019-07-09 14:09:47,310 [myid:3] - INFO  [ListenerThread:QuorumCnxManager$Listener@739] - My election bind port: /172.16.139.16:5888
2019-07-09 14:09:47,312 [myid:3] - ERROR [/172.16.139.16:5888:QuorumCnxManager$Listener@763] - Exception while listening
java.net.BindException: Address not available (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.bind(ServerSocket.java:329)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:742)


2019-07-09 14:09:47,318 [myid:3] - INFO  [QuorumPeer[myid=3]/0:0:0:0:0:0:0:0:2182:FastLeaderElection@818] - New election. My id =  3, proposed zxid=0x1c00003a04
2019-07-09 14:09:47,324 [myid:3] - WARN  [WorkerSender[myid=3]:QuorumCnxManager@588] - Cannot open channel to 1 at election address /172.16.138.205:5888
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:562)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.toSend(QuorumCnxManager.java:538)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.process(FastLeaderElection.java:452)
        at org.apache.zookeeper.server.quorum.FastLeaderElection$Messenger$WorkerSender.run(FastLeaderElection.java:433)
        at java.lang.Thread.run(Thread.java:748)
```

Engineers discovered the master unit was missing the new IP address of the third unit **(contrail_analyticsdb/5)** and that the **my-ids** conlficted with the ordering in the **zoo.conf**

```
version: '2'
volumes:
  analytics_cassandra:
  analytics_zookeeper:
services:
  node-init:
    image: "hub.juniper.net/contrail/contrail-node-init:5.0.2-0.360-queens"
    env_file: /etc/contrail/common_analyticsdb.env
    environment:
      - CONTRAIL_STATUS_IMAGE="hub.juniper.net/contrail/contrail-status:5.0.2-0.360-queens"
    privileged: true
    pid: host
    network_mode: "host"
    volumes:
      - /usr/bin:/host/usr/bin
      - /etc/contrail/ssl:/etc/contrail/ssl
      - /etc/sysctl.d:/etc/sysctl.d
      - /etc/hosts:/etc/hosts
      - /var/log/contrail:/var/log/contrail
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/crashes:/var/crashes
  nodemgr:
    image: "hub.juniper.net/contrail/contrail-nodemgr:5.0.2-0.360-queens"
    env_file: /etc/contrail/common_analyticsdb.env
    environment:
      - NODE_TYPE=database
      - CASSANDRA_CQL_PORT=9042
      - CASSANDRA_JMX_LOCAL_PORT=7200
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - node-init
    depends_on:
      - node-init
    restart: always
  kafka:
    image: "hub.juniper.net/contrail/contrail-external-kafka:5.0.2-0.360-queens"
    network_mode: "host"
    env_file: /etc/contrail/common_analyticsdb.env
    environment:
      - KAFKA_NODES=172.16.138.205,172.16.139.12
      - ZOOKEEPER_NODES=172.16.138.205,172.16.139.12
      - ZOOKEEPER_PORT=2182
      - NODE_TYPE=database
    restart: always
    volumes:
     - /etc/hosts:/etc/hosts
     - /etc/contrail/ssl:/etc/contrail/ssl
  cassandra:
    image: "hub.juniper.net/contrail/contrail-external-cassandra:5.0.2-0.360-queens"
    env_file: /etc/contrail/common_analyticsdb.env
    environment:
      - CASSANDRA_SEEDS=172.16.138.205,172.16.139.12
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=contrail_analytics
      - CASSANDRA_PORT=9160
      - CASSANDRA_CQL_PORT=9042
      - CASSANDRA_SSL_STORAGE_PORT=7011
      - CASSANDRA_STORAGE_PORT=7010
      - CASSANDRA_JMX_LOCAL_PORT=7200
      - NODE_TYPE=database
    volumes:
     - analytics_cassandra:/var/lib/cassandra/data
     - /etc/hosts:/etc/hosts
    network_mode: "host"
    restart: always
  zookeeper:
    image: "hub.juniper.net/contrail/contrail-external-zookeeper:5.0.2-0.360-queens"
    env_file: /etc/contrail/common_analyticsdb.env
    environment:
      - ZOOKEEPER_NODES=172.16.138.205,172.16.139.12
      - ZOOKEEPER_PORTS=4888:5888
      - ZOOKEEPER_PORT=2182
      - NODE_TYPE=database
    volumes:
     - analytics_zookeeper:/data
     - analytics_zookeeper:/datalog
     - /etc/hosts:/etc/hosts
    network_mode: "host"
    restart: alwayscat: .: Is a directory
```

**Comment by dmzoneill** [comment]
[2019-07-08.txt](https://github.com/Juniper/contrail-charms/files/3382578/2019-07-08.txt)

**Comment by dmzoneill** [comment]
We currently have a broken cluster with only 1 leader and slave.. 
We would like instructions to move cluster to working version without causing this issue again

**Comment by Andrey-mp** [comment]
bug with disappearing of cloud_orchestrator was fixed. new Enhancement Request for replacing failed unit will be raised in Juniper's internal Jira.
